
CREATE TABLE IF NOT EXISTS `user` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_name` LONGTEXT, `password` LONGTEXT, `email` LONGTEXT, `time_stamp` BIGINT, `employee_id` BIGINT, `user_type` LONGTEXT, `enabled` BOOLEAN, `uuid` LONGTEXT, `author_id` BIGINT, `user_group_id` BIGINT, `modifier_id` BIGINT, `created_date` LONGTEXT, `modification_date` LONGTEXT, `permission` LONGTEXT, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS `dummy` (`id` BIGINT NOT NULL AUTO_INCREMENT, `uuid` LONGTEXT, `author_id` BIGINT, `user_group_id` BIGINT, `modifier_id` BIGINT, `created_date` LONGTEXT, `modification_date` LONGTEXT, `permission` LONGTEXT, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS `employee` (`id` BIGINT NOT NULL AUTO_INCREMENT, `first_name` LONGTEXT, `middle_name` LONGTEXT, `last_name` LONGTEXT, `dob_day` INT, `dob_month` INT, `dob_year` INT, `ssn` LONGTEXT, `gender` LONGTEXT, `employment_id` LONGTEXT, `department_id` BIGINT, `role_id` BIGINT, `address1` TEXT, `address2` TEXT, `phone1` LONGTEXT, `phone2` LONGTEXT, `uuid` LONGTEXT, `author_id` BIGINT, `user_group_id` BIGINT, `modifier_id` BIGINT, `created_date` LONGTEXT, `modification_date` LONGTEXT, `permission` LONGTEXT, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS `department` (`id` BIGINT NOT NULL AUTO_INCREMENT, `name` LONGTEXT, `description` TEXT, `uuid` LONGTEXT, `author_id` BIGINT, `user_group_id` BIGINT, `modifier_id` BIGINT, `created_date` LONGTEXT, `modification_date` LONGTEXT, `permission` LONGTEXT, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS `role` (`id` BIGINT NOT NULL AUTO_INCREMENT, `name` LONGTEXT, `description` TEXT, `uuid` LONGTEXT, `author_id` BIGINT, `user_group_id` BIGINT, `modifier_id` BIGINT, `created_date` LONGTEXT, `modification_date` LONGTEXT, `permission` LONGTEXT, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS `user_group` (`id` BIGINT NOT NULL AUTO_INCREMENT, `name` LONGTEXT, `description` TEXT, `uuid` LONGTEXT, `author_id` BIGINT, `user_group_id` BIGINT, `modifier_id` BIGINT, `created_date` LONGTEXT, `modification_date` LONGTEXT, `permission` LONGTEXT, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS `user_group_member` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT, `user_group_id` BIGINT, `uuid` LONGTEXT, `author_id` BIGINT, `modifier_id` BIGINT, `created_date` LONGTEXT, `modification_date` LONGTEXT,  PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS `user_group_program_assoc` (`id` BIGINT NOT NULL AUTO_INCREMENT, `program_name` LONGTEXT, `user_group_id` BIGINT, `allow_write` BOOLEAN, `allow_delete` BOOLEAN, `allow_change_permission` TINYINT, `uuid` LONGTEXT, `author_id` BIGINT, `modifier_id` BIGINT, `created_date` LONGTEXT, `modification_date` LONGTEXT,  PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS `staff_invitation` (`id` BIGINT NOT NULL AUTO_INCREMENT, `email` LONGTEXT, `signature` LONGTEXT, `subject` LONGTEXT, `message` TEXT, `uuid` LONGTEXT, `author_id` BIGINT, `user_group_id` BIGINT, `modifier_id` BIGINT, `created_date` LONGTEXT, `modification_date` LONGTEXT, `permission` LONGTEXT, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS `user_login` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT, `in_epoch_time_stamp` BIGINT, `in_time_stamp` LONGTEXT, `live_time` BIGINT, `user_session_id` LONGTEXT, `logout_flag` TINYINT, `logout_state` BOOLEAN, `out_epoch_time_stamp` BIGINT, `out_time_stamp` LONGTEXT, `user_agent` LONGTEXT, `uuid` LONGTEXT, `author_id` BIGINT, `user_group_id` BIGINT, `modifier_id` BIGINT, `created_date` LONGTEXT, `modification_date` LONGTEXT, `permission` LONGTEXT, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS `author` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT, `uuid` LONGTEXT, `author_id` BIGINT, `user_group_id` BIGINT, `modifier_id` BIGINT, `created_date` LONGTEXT, `modification_date` LONGTEXT, `permission` LONGTEXT, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS `modifier` (`id` BIGINT NOT NULL AUTO_INCREMENT, `user_id` BIGINT, `uuid` LONGTEXT, `author_id` BIGINT, `user_group_id` BIGINT, `modifier_id` BIGINT, `created_date` LONGTEXT, `modification_date` LONGTEXT, `permission` LONGTEXT, PRIMARY KEY(id));